### PR TITLE
write draft meta description and meta keywords

### PR DESCRIPTION
**Pull request by McEileen**
Hi, I wrote a draft meta-description and added meta-keywords (should that be hyphenated, one word, or two words?) to our project for SEO improvement.  Please provide feedback, as it is a draft!

### CODE REVIEW

**Comment by vkoves** [comment]
Two things I would point out are that the meta description is too long to show up in a search listing (most search engines top out at 160 characters), and that meta keywords are not needed, as Google (and probably most other search engines), don't use them (see [here](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html)). Otherwise I think this is a great starting point, and if we shorten the meta description we'll be good to go.

**Comment by McEileen** [comment]
Ah, I was unaware of both points.  Thanks for the feedback!

**Comment by TheJhyde** [comment]
This still needs to be updated with a shorter meta description before it can get merged.

**Comment by McEileen** [comment]
Thanks, @TheJhyde!  I will update the description before next Tuesday.

**Comment by McEileen** [comment]
Hi @TheJhyde, @vkoves or @kevinpuj, could one of you please review the new meta description?  It
 squeaked in just under the wire at 159 words! 💅

**Comment by vkoves** [comment]
Apologies for missing this PR. Looks good, so I'm merging it in.

**Comment by McEileen** [comment]
Thank you, @vkoves!

**Pull request merged**
