### PR TITLE
Styled User Sign up form

### PR DESCRIPTION
**Pull request by javierforero**
@McEileen  @vkoves 

Hello, hello.

Here's the styling that I did for the user sign up form.

### CODE REVIEW

**Comment by vkoves** [comment]
This looks good to me, though I'd suggest also implementing the improved styling on the sign in form. It should be just applying this styling to that form as well, which should not be too much trouble and would improve consistency, as it would be weird if one of the forms had good styling and the other didn't. 

However, this can be merged in as is, with sign in being fixed at a later point though if that's more convenient.

You could also improve your styling to take advantage of SCSS nesting (see "Nesting" section of the [SCSS guide](http://sass-lang.com/guide)) if you wish, but that's also not a big deal.

**Comment by javierforero** [comment]
@vkoves 

Yes, that is a great point. I refactored the code to use more of the scss nesting features. I also added the same styling to the user sing in form in my latest commit to this branch. Please review and let me know if it all looks good to ya

**Comment by vkoves** [comment]
Great stuff! Sign in looks a lot better. However I found one last issue that should be resolved, which is mobile.

 As you can see from this screenshot, the form fields and submit button cut off on the sides of mobile devices, as they have a width of 400px, which is larger than many mobile device's emulated pixel width. To fix this issue, you should be able to just add `max-width: 100%;` to your form fields and buttons, which will prevent them from becoming larger than their parent container.

Overall really excited to see this deployed, it's a huge improvement in the polish of the sign in and sign up pages. Good work! :+1:

**Comment by javierforero** [comment]
@vkoves 

Sweet deal. Okay, I think I fixed it so now it's semi responsive. Please see my latest commit "semi responsive edit". 
We might want to later write a media query (for the iPhone5 view) since I think the input fields might see a bit too tall.

**Comment by javierforero** [comment]
@vkoves @McEileen  I realized I don't have you guy's phone numbers. I just wanted to let you know that I can't make it tonight. Something came up at work. I am not abandoning the project, I swear!

**Comment by McEileen** [comment]
This looks good!  I'm doing a very quick review of activity on the repo
before bed, then my goal is to approve the change tomorrow during lunch or
before hack night.  Good work, Javier.  (Would you prefer if I approve the
change right away or wait for you to make the mobile fix Viktor pointed
out?)

**Comment by javierforero** [comment]
Hi @McEileen 

I did the mobile edit in the latest commit called "semi responsive edit". Are you still seeing the form overflow?

**Comment by vkoves** [comment]
I think that comment was delayed, as it says it was submitted via email, and that she was checking work "before bed". I've double checked and everything looks fine, though I don't think the `width: 80%` on the form is necessary (it just makes the fields take up less space on mobile), so I would remove that.

**Comment by McEileen** [comment]
Hi @javierforero, this looks great!  I'm about to approve it.  Also, @vkoves was correct, I sent that comment via email last night at about 10 p.m., and for some reason it showed up late?  Not sure why......

**Pull request merged**
