### PR TITLE
Block list

### PR DESCRIPTION
**Pull request by TheJhyde**
This should fix https://github.com/Tweechable/tweechable_final/issues/29 and lay the foundation for fixing https://github.com/Tweechable/tweechable_final/issues/25. Users can unsubscribe from receiving lessons from tweechable by tweeting "@tweechable STOP". The app also has the ability to prevent people from sending tweets but there's is no way to add people to that list yet.

I wrote some tests for this but in order to maintain blocks when people change their screen name, I had to rewrite how mentions are generated which would break all the old mention unit tests. So they're commented out at the moment, I may come back and try to fix them or build something equivalent.

### CODE REVIEW

**Comment by kevinpuj** [comment]
In discussion on 1.17, we discussed a near-future state in which Tweechable admins (business users, not developers) could block someone from triggering Tweechable.  This could be accomplished via Tweechable twitter acct or the admin panel.

We discussed a farther future state in which Tweechable app logic would look at specific variables about users triggering tweechable (number of times triggered, number of followers, number of times causing others to unsubscribe from Tweechable), and use that to build automated behavior as to whether they are using it maliciously.

**Comment by TheJhyde** [comment]
Based on last night's conversation, I added a form on the web app to create blocks.

**Comment by vkoves** [comment]
Discussed in person, but please add an admin page where this can be accessed, and move the "Contribute a New Lesson" page to the admin page as well, since currently you can't access it otherwise.

**Comment by McEileen** [comment]
Hi @TheJhyde, this looks really good and I am going to merge it, but with a caveat.
I wasn't able to log in locally and test the admin panel because a) the only user I had in the database was a non-admin user and I couldn't create a new user and b) when I tried to log in with the non-admin user, I got the `undefined local variable or method 'encrypted_password' for #<User:0x007fdfae6e9a48>` error that we saw a couple hack nights ago when looking at the devise issues.

**Comment by McEileen** [comment]
I'm going to bend the rules about not merging our own PRs because @TheJhyde approved these changes for me and I want to close our last issue with the MVP milestone.  

At hack night Tuesday @TheJhyde  told me that he had already written tests that covered the mention model and they pass.  He had commented them out because he needed to put in actual Twitter credentials to make them pass.  

I had thought that the mention tests were all broken, because of what @TheJhyde  wrote for PR #72 below 

> I wrote some tests for this but in order to maintain blocks when people change their screen name, I had to rewrite how mentions are generated which would break all the old mention unit tests. So they're commented out at the moment, I may come back and try to fix them or build something equivalent.

I wrote more mention tests (even though it wasn’t part of the issue) because I thought it would be good to increase test coverage.  Now that I realize I may have written redundant tests, I have learned the lesson of staying focused on the github issue!  Also, I’m not sure if we should leave in the old tests Julian had written for the Mention model, keep the ones I wrote or somehow combine the two.  I’m merging this for now, but if people want we can change the mention tests later.  Maintaining tweet order is obviously the most important part.

**Pull request merged**
