### PR TITLE
Remove EZ Gem and Fix Migration

### PR DESCRIPTION
**Pull request by TheJhyde**
This pull request should fix it so the devise migration can go through. In order to do this I removed the ez gem, which means changes to the database will need migrations instead of changing the models.yml file. I think this is better in the long run - it's confusing to do our migrations in a nonstandard way.

I also revised the seed file so it's simpler and matches the current state of the database.

### CODE REVIEW

**Comment by McEileen** [comment]
Hi @TheJhyde, the changes you made make sense to me, but the travis check is failing, and it says that the relation users does not exist... I checked out your branch on my local and I got the same error when I dropped, then tried to recreate the database.  I saw you mention on slack that "the schema was set so it thought the migration had already been run."  Do we still need to make that  change?  Let me know, thanks.

**Comment by McEileen** [comment]
Hi @TheJhyde, I deleted all migrations and made a new one based off the schema.  I also found we were using `username` for user in some spots, and `name` in others.  I changed all instances of `username` to `name`, but have not yet deleted `name` from the log-in form.  (I'll do that later.)  Log-in currently isn't working..... Not sure why, but will continue looking into it.
Congratulations on your new job!  🎆 🍾 🎆 I hope your coworkers are nice.

**Comment by vkoves** [comment]
@McEileen - I see you added a new commit removing the name from login, does this make the login form work? I'll be double checking this myself, but I'd like to get a list of tasks required to merge in this PR

**Comment by vkoves** [comment]
Just fixed the user login not working, and have verified it myself that it works. @McEileen or @TheJhyde - please do a final review and merge this in (and deploy to production) ASAP if it works. PR #94 should also be ready, so if you are doing a deploy and that looks fine, please put that in as well.

**Pull request merged**
