### PR TITLE
141/fix response system

### LINKED ISSUE #141: Current response system is broken
The response system currently doesn't work.
1) The replies include the educatee's handle, but not an @ symbol before the educatee's handle.  This means they'll likely never see the response.
2) When I tested the app locally with a test tweechable account, the bot tweeted at both the educatee and the test tweechable account.  I'm not sure if this would happen when responding from the actual tweechable account - we might have hardcoded in the tweechable name to be removed from any replies?

### PR DESCRIPTION
**Pull request by McEileen**
Hi @vkoves, could you please review these changes?  In response to issue #141, I added an @ before the educatee's handle and fixed the code so Tweechable won't tweet at itself.  Thanks!

fixes #141

### CODE REVIEW

**Comment by McEileen** [comment]
Hey @vkoves, could you please help me get unstuck on the test I'm trying to write?  There was a test helper method meant to generate a tweet with `user_mentions`, called `generate_tweet_with_author_and_mentions`.  However, when I ran it the resulting tweet object didn't have any user_mentions.  (The generate author functionality does seem to work fine.)  I looked up the documentation on `user_mentions` and added the `indices` as parameters for each user in `user_mentions`, but still, no dice!  
Any help would be appreciated, thanks.

**Comment by vkoves** [comment]
@McEileen - it took a good bit of digging, but I think I got the issue resolved. The `user_mentions` seem to be needed to be passed inside of an `entities` hash, which I discovered by digging through the tests of the Twitter gem and finding [this line](https://github.com/sferik/twitter/blob/d7951759da897e6a8e3ed0069b2e850470991e3f/spec/twitter/tweet_spec.rb#L456) that generates a tweet with mentions. Their documentation didn't seem to reference this, but I think that's probably because they don't expect folks to be making full tweet objects with `user_mentions` like we are.That's just a guess though, since I am not too familiar with the Twitter gem.

**Comment by McEileen** [comment]
@vkoves Thanks for all of the digging!  The `user_mentions` formatting issue was messing up other `test_helper` methods, but I refactored to make the test coverage more complete.

Now I'm having a hard time figuring out how to test that the bot sends a tweet which includes the potential educatee's handle with an `@` before it.  I hoped the `If a mention is well formatted, it will trigger a tweet that contains the educatee's handle with an @ symbol before it` test would work, but the issue is that `Mention.reply_mentions` returns mentions, not tweets.  I'm not sure how to test the tweet content, `to_send`, that is generated on line 58.  In JUnit I'd use a captor, but I'm not sure how to do something for Ruby on Rails.  Any ideas?  Thanks!

**Comment by vkoves** [comment]
@McEileen - that is a great question, but unfortunately I've been unable to figure out how to do that. Especially since the `Mention.reply_mentions` method generates a new `Twitter_API` object itself, it would be tricky to do, but I am also not sure how to handle spying on functions in Ruby either :disappointed: 

I found [this article](https://semaphoreci.com/community/tutorials/mocking-in-ruby-with-minitest) that should be helpful for this, but I couldn't get it to work; perhaps you can figure it out though?

**Comment by McEileen** [comment]
That article looks helpful, thank you!  I want to deploy the fixes, so I am going to merge in the changes 
(including the commented out failing test) and deploy, then close issue 141.  However, I am going to make a new, spin-off issue for testing that the tweet content includes `@` before the educatee's handle.  I'll assign myself to that issue, too.  (I'm not sure if spin-off issues are best practice for OSS..... Please let me know if you don't agree.)

**Comment by vkoves** [comment]
That seems fine. Since this is such a small change and unlikely to break again, I think manually testing it and then taking the testing on later should be sufficient.

**Pull request merged**
